services:
  app:
    environment:
      TG_TOKEN: ${TG_TOKEN}
      TG_LOGGER_TOKEN: ${TG_LOGGER_TOKEN}
      TG_LOGGER_CHAT_ID: ${TG_LOGGER_CHAT_ID}
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - backend


networks:
  backend: