name: main

on:
  push:
    branches: [ "main" ]

env:
  BIN_PATH: ./bin
  
jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml

  deploy:
    needs: [test, lint]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: store envs
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: build
        run: env GOOS=linux CGO_ENABLED=0 go build -o $BIN_PATH/service ./cmd/service

      - name: deploy to prod
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SOURCE: ./
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}
          SCRIPT_AFTER: |
            cd outfit-bot
            echo "start running bot...."
            docker compose down && docker compose build --no-cache && docker compose up -d
