name: prepare

on:
  workflow_call:

env:
  BIN_PATH: ./bin

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: build
        run: go build -o $BIN_PATH/service ./cmd/service

  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.59

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: test
        run: env TG_LOGGER_TOKEN=test TG_LOGGER_CHAT_ID=3333 go test ./... -v -tags unit -race